Repository forgeflux-org/interface, pull requests merged in 2021-11, with the labels that each got.

#16 Notification System Fix
  interface/forges/gitea.py
  interface/forges/github.py
  interface/forges/notifications.py
  interface/forges/payload.py
Labels: bug

#25 Load configuration using dynaconf
  config/.env-sample
  config/settings.toml
  interface/__main__.py
  interface/app.py
  interface/db.py
  interface/forges/gitea.py
  interface/forges/github.py
  interface/git.py
  interface/local_settings_example.py
  interface/ns.py
  interface/runner.py
  interface/settings.py
  requirements.txt
Labels: enhancement

#23 Addition of initial OpenAPI specification
  Makefile
  docs/openapi/api/v1/components/responses/repo_info.yaml
  docs/openapi/api/v1/components/schema/issue.yaml
  docs/openapi/api/v1/components/schema/pull_request.yaml
  docs/openapi/api/v1/components/schema/repo_link.yaml
  docs/openapi/api/v1/components/schema/subscribe.yaml
  docs/openapi/api/v1/spec.yaml
  docs/openapi/openapi.yaml
  docs/openapi/package-lock.json
  docs/openapi/package.json
  docs/openapi/yarn.lock
Labels: documentation
